name: 'Transfer file'
description: 'Transfers an file generated during the workflow to an post url'
inputs:
  file-path:
    description: 'file to transfer'
    required: true
  name:
    description: 'the name of the package'
    required: true
  version:
    description: 'the version of the package'
    required: true
outputs:
  time:
    description: 'The time the transfer was completed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file-path }}
    - ${{ inputs.name }}
    - ${{ inputs.version }}